# 2-3. Load a pandas.DataFrame

이 실습에서는 ```tf.data.dataset```을 사용하여 pandas dataframes를 로드하는 방법에 대한 예를 제공합니다.

***

Cleveland Clinic Foundation for Heart Disease에서 제공하는 작은 데이터 세트를 사용합니다.

CSV에는 수백 개의 행이 있습니다.

각 행은 환자를 설명하고, 각 열은 속성을 설명합니다.

이 정보를 사용하여 환자가 심장병에 걸렸는지 여부를 예측할 수 있습니다. 

이 데이터 세트는 binary classification 작업입니다.

***

## 1. Read data using pandas

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import pandas as pd
import tensorflow as tf

Download the csv file containing the heart dataset.

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')

Read the csv file using pandas.

In [3]:
df = pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [20]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal           int8
dtype: object

In [6]:
df['thal']

0           fixed
1          normal
2      reversible
3          normal
4          normal
          ...    
298         fixed
299    reversible
300    reversible
301    reversible
302    reversible
Name: thal, Length: 303, dtype: object

***

dataframe에서 ```object```인 ```thal``` 열을 별도의 numerical value(숫자 값)로 변환합니다.

In [7]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [8]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

***

## 2. Load data using tf.data.Dataset

pandas dataframe 으로부터 값을 읽기 위해 ```tf.data.Dataset.from_tensor_slices```을 사용합니다.

```tf.data.Dataset```을 사용하면 간단하고 효율적인 데이터 파이프라인을 작성할 수 있다는 이점이 있습니다. 

In [9]:
target = df.pop('target')

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [11]:
for feat, targ in dataset.take(5):
    print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


***

```pd.Series```는 ```__array__``` 프로토콜을 구현하므로 거의 모든 곳에서 ```np.array``` 또는 ```tf.Tensor```를 사용할 수 있습니다.

In [12]:
tf.constant(df['thal'])

<tf.Tensor: id=21, shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3

***

Shuffle and batch the dataset.

In [13]:
train_dataset = dataset.shuffle(len(df)).batch(1)

***

## 3. Create and train a model

In [14]:
def get_compiled_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(1)
    ])

    model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
    return model

In [15]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Epoch 1/15
303/303 [==============================] - 3s 10ms/step - loss: 2.0115 - accuracy: 0.7063
Epoch 2/15
303/303 [==============================] - 1s 3ms/step - loss: 0.9197 - accuracy: 0.6634
Epoch 3/15
303/303 [==============================] - 1s 3ms/step - loss: 0.7271 - accuracy: 0.7195
Epoch 4/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6448 - accuracy: 0.7327
Epoch 5/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6173 - accuracy: 0.7228
Epoch 6

***

## 4. Alternative to feature columns (특성 컬럼 대체)

dictionary를 input으로 모델에 전달하는 것은 

```tf.keras.layers.Input``` 레이어의 일치하는 dictionary를 만들어 pre-processing을 적용하고 functional api를 사용하여 이를 쌓는 것만큼 쉽습니다.

(Passing a dictionary as an input to a model is as easy as creating a matching dictionary of ```tf.keras.layers.Input layers```, 

applying any pre-processing and stacking them up using the functional api.)

이 것을 feature columns의 대안으로 사용할 수 있습니다.

In [24]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

```tf.data```와 함께 사용할 때 ```pd.DataFrame```의 열 구조를 보존하는 가장 쉬운 방법은 ```pd.DataFrame```을 dict으로 변환하고 해당 dictionary을 slice 하는 것입니다.

In [17]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [18]:
for dict_slice in dict_slices.take(1):
    print (dict_slice)

({'age': <tf.Tensor: id=14746, shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: id=14754, shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: id=14749, shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: id=14758, shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: id=14748, shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: id=14751, shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: id=14753, shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2,

In [19]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 1s 64ms/step - loss: 7.3186 - accuracy: 0.2739
Epoch 2/15
19/19 [==============================] - 0s 4ms/step - loss: 5.2941 - accuracy: 0.2541
Epoch 3/15
19/19 [==============================] - 0s 4ms/step - loss: 3.5523 - accuracy: 0.2574
Epoch 4/15
19/19 [==============================] - 0s 4ms/step - loss: 2.3376 - accuracy: 0.2937
Epoch 5/15
19/19 [==============================] - 0s 4ms/step - loss: 1.4976 - accuracy: 0.4191
Epoch 6/15
19/19 [==============================] - 0s 4ms/step - loss: 1.0276 - accuracy: 0.5974
Epoch 7/15
19/19 [==============================] - 0s 4ms/step - loss: 0.9128 - accuracy: 0.6370
Epoch 8/15
19/19 [==============================] - 0s 4ms/step - loss: 0.8365 - accuracy: 0.6502
Epoch 9/15
19/19 [==============================] - 0s 4ms/step - loss: 0.7786 - accuracy: 0.6535
Epoch 10/15
19/19 [==============================] - 0s 4ms/step - loss: 0.7355 - accuracy: 0.6766
Epoch 11/15
19/19 